name: your_app_name
description: A description for your app
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.5
  chewie: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
